### PR TITLE
Remove motion-yaml 1.4. lock

### PR DESCRIPTION
**Pull request by Atastor**
Thats an older patch which I so far only used privately. It might help with going to rm 5.5+, there were some difficulties in the beginning.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
@wndxlori I gave you access to all our RubyMotion repos. You’ll need to get ruby gems access too which I can’t do from mobile.

**Comment by kemiller** [comment]
@wndxlori I added you to the cdq gem.

**Comment by cmckni3** [comment]
Any update on this?

**Comment by andrewhavens** [comment]
Instead of hard-coding this to `= 1.6` maybe it should be `>= 1.4`?

**Comment by cmckni3** [comment]
I agree with that. I am running into other gems that have strict versions. Usually gems that depend on `motion-cocoapods`

**Comment by wndxlori** [comment]
Hmmm.  Why do I not have write access on this repo again?  (I see can can publish the gem though!)

Hey @Atastor if you can update this PR as per the recent suggestions, we can get this merged in before we release.

**Comment by wndxlori** [comment]
👍

**Pull request closed without merging**
