### PR TITLE
Adds opt-in support for logging via motion_print

### PR DESCRIPTION
**Pull request by markrickert**
https://github.com/OTGApps/motion_print#woah-this-is-great-how-can-i-make-my-gem-support-motion_print

cc @GantMan @colinta

### CODE REVIEW

**Comment by markrickert** [comment]
lol

> Containers/Data/Application/A8AD02B4-2FF3-4B12-B51C-A94E213388F6/Documents/CDQ.sqlite.  SQLite error code:1802, 'not an error'";

**Comment by colinta** [comment]
Very nice!  Now how does one go about fixing a "not an error" error??

**Comment by GantMan** [comment]
this is not the error you're looking for... move along.... move along...

**Comment by GantMan** [comment]
@markrickert  we should divide up some common objects so we don't step on each other's toes with opt-in PRs :)  I plan on making a few myself, once "not an error" errors can be understood.

**Pull request merged**
