### PR TITLE
Removes iCloud support, since it was deprecated back in iOS 10.

### PR DESCRIPTION
**Pull request by wndxlori**
Since it's also causing a lot of flaky build errors, this should be 👍👍.  

Also bumped the version number, because removing a feature like that is a breaking change for anyone using it.

### CODE REVIEW

**Comment by wndxlori** [comment]
Oh, FFS.

**Comment by wndxlori** [comment]
Sigh. Now it's a build/license/version issue.

**Comment by wndxlori** [comment]
Yay. Merge it, quick.

**Comment by andrewhavens** [comment]
Done. Nice work @wndxlori and @cmckni3!

**Pull request merged**
