### PR TITLE
Fix broken Travis config

### LINKED ISSUE #142: [ci] Travis CI failing
```
sudo chown -R travis ~/Library/RubyMotion
chown: /Users/travis/Library/RubyMotion: No such file or directory
The command "sudo chown -R travis ~/Library/RubyMotion" failed and exited with 1 during .
```

### PR DESCRIPTION
**Pull request by andrewhavens**
This PR will fix the broken Travis config and simplify it a little bit by removing unnecessary config options.

Fixes #142

### CODE REVIEW

**Comment by cmckni3** [comment]
#140 updates deps to fix the `json` installation error

**Comment by andrewhavens** [comment]
Travis build is still failing due to bug that is fixed in #141

**Comment by digitalmoksha** [comment]
@andrewhavens 

@amirrajan and I worked on getting Travis builds working again for RubyMotion.  He came up with https://github.com/amirrajan/RubyMotionObjectiveC/blob/master/.travis.yml  (and I also use it at https://github.com/digitalmoksha/motion-html-pipeline/blob/master/.travis.yml)

The key is that it no longer relies on RM being in distributed in the xcode image, like it used to be.  RM is now downloaded and installed.

Here's the slack conversation: https://motioneers.slack.com/archives/C055RDLS0/p1560008301052800

**Comment by digitalmoksha** [comment]
We do need to get that documented in a more discoverable place... 😓

**Pull request merged**
