### PR TITLE
CDQRelationshipQuery seems to have cycled reference.

### PR DESCRIPTION
**Pull request by katsuyoshi**
I checked it with debug print.  This code ffc8b8c .
It shows all objects was released.

### CODE REVIEW

**Comment by katsuyoshi** [comment]
And I doubt extended sets by CDQRelationshipQuery.extend_set is released.
But I don't know the way to check it now.

**Comment by digitalfx** [comment]
Hi Katsuyoshi, I am finding just that with extend_set (and others). I have created an issue here #80, which includes a test project that you can profile to see memory growth. I hope this helps you.

**Comment by katsuyoshi** [comment]
Thank you @digitalfx.
I have not much a time for testing now.
If I have time, I'll try it.

**Comment by kemiller** [comment]
I think you are right that there are cycles in there, and also with CDQObjectProxy.  But I don't think just adding weak refs is OK, because it might result in dangling references instead.  I'm going to have to think through the life cycle a bit more.

**Comment by kemiller** [comment]
Actually I do think this is right, but it won't work right in the CDQObjectProxy case.  But that's a lower priority, I don't think many people are using that, and we should probably do it differently.

**Comment by katsuyoshi** [comment]
@kemiller, I agree to your point. Using weak ref is a little bit tricky I think so.
I think you handled it well.

**Pull request merged**
