### PR TITLE
Allow updates to an object for multiple properties.

### PR DESCRIPTION
**Pull request by markrickert**
with specs and docs of course :)

### CODE REVIEW

**Comment by jamonholmgren** [comment]
:+1: :100:

**Comment by citrus** [comment]
This is awesome. Great work! 👍👍

**Comment by dam13n** [comment]
Just curious - is there a reason not to sanitize for the user by default?

**Comment by markrickert** [comment]
Trying to follow ActiveRecord's lead and raise an exception. If Ken has and strong feeling either way, I'm open to being pursuaded to change it.

**Comment by kemiller** [comment]
I don't have super-strong feelings one way or the other, but I slightly prefer your way, Mark.

**Comment by markrickert** [comment]
Yeah, I understand that sometimes you have things that get returned from an API or whatever that contain more properties than your actual data model, but I'm not keen on putting the cleansing burden on CDQ.

**Comment by dam13n** [comment]
Helpful to hear your explanations. Thanks.

**Comment by paddingtonsbear** [comment]
Hey @kemiller, is there any reason why this has not been merged yet ?

**Comment by kemiller** [comment]
Indolence, mostly.  I think travis was being slow last time i looked at it, but there's no particular reason it can't be merged.

**Comment by paddingtonsbear** [comment]
:+1:

**Comment by markrickert** [comment]
WOOHOO!

**Pull request merged**
