### PR TITLE
Adds some more granulatiry to remove_all spec

### PR DESCRIPTION
**Pull request by markrickert**
So that we can be sure that when removing the relationships that the original objects aren't deleted.

### CODE REVIEW

**Comment by markrickert** [comment]
Not sure why this is failing on travis. It passes all tests on my local machine.

**Comment by cmckni3** [comment]
Could probably merge master into the branch and they would pass. Unless those tests were removed as part of #150

**Comment by markrickert** [comment]
Ahh the forgotten 4 year old pull request 😆

**Comment by cmckni3** [comment]
😆 yeah sorry. Tests should be good after recent clean up by @wndxlori

**Comment by markrickert** [comment]
OMG IT WORKED! hahaha

**Pull request merged**
